CREATE TABLE IF NOT EXISTS BeznyUcet (
    UserID INTEGER NOT NULL,
    AccID INTEGER PRIMARY KEY AUTOINCREMENT,
    Zustatek INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);