CREATE TABLE IF NOT EXISTS KreditniUcet(
    UserID INTEGER NOT NULL,
    AccID INTEGER PRIMARY KEY AUTOINCREMENT,
    Zustatek INTEGER NOT NULL DEFAULT 0,
    termin_splatnosti DATE NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);